apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-store
  template:
    metadata:
      labels:
        app: grocery-store
    spec:
      containers:
        - name: grocery-store
          image: alay2003/grocery-store:alay  # Use the correct image tag here
          ports:
            - containerPort: 3000
