apiVersion: v1
kind: Service
metadata:
  name: grocery-store
spec:
  type: LoadBalancer  # Changed to LoadBalancer
  ports:
    - port: 3000        # The port that the service will expose
      targetPort: 3000  # The port the container is listening on
  selector:
    app: grocery-store
