apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.0.0
        ports:
          - containerPort: 5044
        volumeMounts:
          - name: logstash-config
            mountPath: /usr/share/logstash/pipeline/
        env:
          - name: ELASTICSEARCH_HOST
            value: "elasticsearch:9200"
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk1
spec:
  ports:
    - port: 5044
      targetPort: 5044
  selector:
    app: logstash
  type: NodePort
